#!/usr/bin/python

import autober
from sys import stdout,argv

if __name__ == '__main__':
	for x in argv[1:]:
		lex = autober.lexer(open(x))
		parser = autober.parser(lex)
		p = parser.parse_tree()
		ast = autober.semantics(p)

		codec = autober.codec.c(ast)
		f = open("autober.h", 'w')
		#f = stdout
		codec.write_header(f)
