#!/usr/bin/python

import autober
from sys import stdout,argv

if __name__ == '__main__':
	for x in argv[1:]:
		lex = autober.lexer(open(x))
		parser = autober.parser(lex)
		p = parser.parse_tree()
		ast = autober.semantics(p)

		codec = autober.codec.c(ast)
		h_file = "auto_" + codec.modname + ".h"
		c_file = "auto_" + codec.modname + ".c"
		h = open(h_file, 'w')
		#h = stdout
		codec.write_header(h)
		c = open(c_file, 'w')
		#c = stdout
		codec.include(h_file)
		codec.write_code(c)
