#!/usr/bin/python

import autober
from sys import stdout,argv

if __name__ == '__main__':
	ecode = 0

	for x in argv[1:]:
		try:
			lex = autober.lexer(x)
			parser = autober.parser(lex)
			p = parser.parse_tree()
			ast = autober.semantics(p)
			ast.parse_tree.pretty_print()
		except autober.AutoberException, e:
			print str(e)
			ecode += 1
			continue

		target = autober.target.c(ast)
		h_file = target.modname + ".h"
		c_file = target.modname + ".c"
		h = open(h_file, 'w')
		#h = stdout
		target.write_header(h)
		c = open(c_file, 'w')
		#c = stdout
		target.include(h_file)
		target.write_code(c)
	
	raise SystemExit, ecode
